import PySimpleGUI as sg
from Import_audio import Import_audio
from Record_audio import Record_audio
import datetime
import os
# All the stuff inside window.

sg.theme('LightBlue')
count = 0
playing=0
now = datetime.time()

# Format the date and time
current_time = now.strftime("%M:%S")

# ------ Menu Definition ------ #
menu_def = [['File', ['Import Files']],['Edit', ['Trim','Overwrite']],['9', ['oo']],['Help', ['About...']]]
# ------ Frame Definition ------ #
header = ["Name","Date","Length"]
rows=[["Song 1","22/2/2024","11:26"],["Song 1","22/2/2024","11:26"],["Song 1","22/2/2024","11:26"]] #generated by os.dir
frame_layout_1=[[sg.Text('Recording List:'),sg.Button('Import Files')],[sg.Table(headings=header,values=rows,key="-TABLE-")]]
layout = [[sg.Menu(menu_def)],
          [sg.Frame('',frame_layout_1,element_justification='center'), sg.VerticalSeparator(color='black'), sg.Graph((400, 200), (-400, -200), (400, 200), background_color='white', key='-GRAPH-')],
          [sg.Output(size=(30, 1))],
            [sg.Text(current_time),sg.ProgressBar(1000, key='-PROGRESS_BAR-',size=(50,10))],
            [sg.Button('🎤',font=(30),key='Record'),sg.Button('▶',font=(40),key='Play'),sg.Button('⏸',font=(40),key='Pause'),sg.Button('⏹️',font=(40),key='Stop'),sg.Button('⏮',font=(40),key='Fast Backward'),sg.Button('⏭',font=(40),key='Fast Forward'),sg.Button('💾',font=(30),key='!Save'),sg.Button('🗑',font=(30),key='!Delete'),sg.Text("Volume"),sg.Slider((1, 100), orientation='horizontal')]]


# Create the Window
window = sg.Window('Sound Recorder', layout, resizable=True)
window.finalize()
# Event Loop to process "events" and get the "values" of the inputs
while True:
    event, values = window.read()
    if playing ==1:
        pass
    

    if event == sg.WIN_CLOSED:
        break
    elif event == 'Import Files':
        Import_audio() #return [[],[]]
        pass
    elif event == 'Record':
        Record_audio()
        pass
    elif event == 'Play':
        playing=1
    elif event == 'Pause':
        playing=0
    elif event == 'Stop':
        playing=0
        count=0
    else:
        print(event,values)           
    window['-PROGRESS_BAR-'].update(current_count=count)
window.close()

''',[sg.Input(), sg.FileBrowse('FileBrowse')],
    [sg.Input(), sg.FolderBrowse('FolderBrowse')],
    [sg.Submit(), sg.Cancel()]'''
